import React from "react";
import Navbar from "./(koinx)/components/Navbar";
import "./global.css";
import Cryptocurrencies from "./(koinx)/components/Cryptocurrencies";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <div>
          <Navbar />
          <Cryptocurrencies />
        </div>
      </body>
    </html>
  );
}
